from . import hr_employee
from . import hr_contract
from . import hr_contract_template
from . import hr_employee_card
from . import hr_employee_move
from . import hr_employee_resigned
from . import res_partner_bank
from . import hr_department
from . import setting